# Docker Compose for Local CI/CD Testing
# Use this to avoid PostgreSQL port conflicts during local testing

version: '3.8'

services:
  postgres-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: test_password
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
    ports:
      # Use a different port to avoid conflicts with local PostgreSQL
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge